//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YEF.Models.EDMXDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysOrganizations
    {
        public SysOrganizations()
        {
            this.SysUsers = new HashSet<SysUsers>();
            this.SysRoles = new HashSet<SysRoles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Describe { get; set; }
    
        public virtual ICollection<SysUsers> SysUsers { get; set; }
        public virtual ICollection<SysRoles> SysRoles { get; set; }
    }
}
