//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YEF.Models.EDMXDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRoles
    {
        public SysRoles()
        {
            this.SysUsers = new HashSet<SysUsers>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public string RoleDescribe { get; set; }
        public string RoleAuthority { get; set; }
    
        public virtual SysOrganizations SysOrganizations { get; set; }
        public virtual ICollection<SysUsers> SysUsers { get; set; }
    }
}
