//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YEF.Models.EDMXDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEFOrganization
    {
        public YEFOrganization()
        {
            this.YEFUsers = new HashSet<YEFUser>();
            this.YEFRoles = new HashSet<YEFRole>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Describe { get; set; }
    
        public virtual ICollection<YEFUser> YEFUsers { get; set; }
        public virtual ICollection<YEFRole> YEFRoles { get; set; }
    }
}
